### ISSUE TITLE
enable wiki on this repository

### ISSUE THREAD

**Issue by paulvi** [xolstice/protobuf-maven-plugin#19]
Could you enable wiki on this repository.

That would possibly fit more for IDE notes, than updating README

ref #10 #16 #18

**Comment by sergei-ivanov** [comment]
Hi Paul, 

I enabled the wikis temporarily with public access (so that you should be able to contribute directly).
Unfortunately, there seem to be only two options available: editable by project members only, or editable by everyone. There seem to be no pull-request driven workflow available for the wikis. If free-for-all editing results in abuse or vandalism, I shall have to lock it down.
Another thing is, I am a bit wary of the idea of having multiple scattered sources of information. There's currently the readme file, which is quite minimal, and there's the generated plugin site. Wiki adds yet another documentation space here, and it may become confusing.
But please give it a go. Let's see where it takes us.

Kind regards,
Sergei

**Comment by paulvi** [comment]
OK, thanks

Just close it, when it make less good than evil.

**Comment by paulvi** [comment]
P.S. I tried to add https://github.com/xolstice/protobuf-maven-plugin/issues/15 reply to wiki, but it failed 

I think it should be public.

**Comment by sergei-ivanov** [comment]
Hm, but it is public!
