### ISSUE TITLE
Does this plugin always expect the proto files to be in src/main/proto ?

### ISSUE THREAD

**Issue by asif31iqbal** [xolstice/protobuf-maven-plugin#6]
Is there any way I can specify a custom directory for the proto files instead of src/main/proto ?

**Comment by sergei-ivanov** [comment]
Yes, you can configure it using `protoSourceRoot` parameter.
Please take a look at the documentation:
https://www.xolstice.org/protobuf-maven-plugin/compile-mojo.html#protoSourceRoot

Also, it may be more productive to ask simple questions on gitter first instead of filing issues for them.
You can sign in with your github account:
https://gitter.im/xolstice/protobuf-maven-plugin

**Comment by btiernay** [comment]
It seems to have issues with `import` pathing when using `protoSourceRoot`. I think the current directory needs to be set or something when calling `protoc`. Should I create a ticket for this?

**Comment by btiernay** [comment]
Please disregard. This was an error of not including protobuf as a dependency.
