### ISSUE TITLE
Is it can build on jdk x32 on windows?

### ISSUE THREAD

**Issue by ghost** [xolstice/protobuf-maven-plugin#69]
Is it can build on jdk x32 on windows?

**Comment by sergei-ivanov** [comment]
A short answer is "I have no idea!".

A longer answer is: you may need to try it yourself, if you have Windows and a 32-bit JDK, because I don't have either of them. In theory it should not be a problem, because Maven plugin is a standard Java (it does not care much whether it is 32-bit or 64-bit), and it executes `protoc` process that has versions for Windows available.
