### ISSUE TITLE
If outputDirectory parameter is specified grpc-java plugin fails to generate message sources

### ISSUE THREAD

**Issue by Alvkoen** [xolstice/protobuf-maven-plugin#8]
- Take tutorial .proto file from https://github.com/grpc/grpc-java/blob/master/examples/src/main/proto/route_guide.proto
- Try to run plugin with the following config.
- If an outputDirectory parameter is specified in config, plugin generates only one file for grpc service (even if we have a property option java_multiple_files = true; in a .proto file) and fails to generate message sources. 
- Build then fails with multiple errors "cannot find symbol" indicating that it couldn't find any message sources that are stated in a grpc service as input or return parameters.

Output of mvn --version command: 

```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T19:41:47+03:00)
Maven home: /Users/aleksandrakoen/Maven/apache-maven-3.3.9
Java version: 1.8.0_91, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.9.5", arch: "x86_64", family: "mac"

```

Running maven from command line.

Plugin configuration that doesn't work:

```
  <extensions>
            <extension>
                <groupId>kr.motd.maven</groupId>
                <artifactId>os-maven-plugin</artifactId>
                <version>1.4.0.Final</version>
            </extension>
        </extensions>

        <plugins>
            <plugin>
                <groupId>org.xolstice.maven.plugins</groupId>
                <artifactId>protobuf-maven-plugin</artifactId>
                <version>0.5.0</version>
                <configuration>
                    <protocArtifact>com.google.protobuf:protoc:3.0.0-beta-2:exe:${os.detected.classifier}
                    </protocArtifact>
                    <pluginId>grpc-java</pluginId>
                    <pluginArtifact>io.grpc:protoc-gen-grpc-java:0.14.0:exe:${os.detected.classifier}</pluginArtifact>
                    <protoSourceRoot>${basedir}/src/main/resources</protoSourceRoot>
                    <outputDirectory>${basedir}/target/generated-sources</outputDirectory>
                </configuration>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>compile</goal>
                            <goal>compile-custom</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by sergei-ivanov** [comment]
Hello @Alvcohen,

To start with, I do not think that `option java_multiple_files = true;` is being honoured by gRPC code generator. To the best of my knowledge and belief, it only applies to generating java code for the messages (`--java_out`).

But I believe your problem is elsewhere: your output directory is reused between the two goals. Unless there is a good reason to put all generated sources in the same output directory, it's better to _not_ alter the default configuration (Maven will handle multiple source directories correctly, and so will IDEA/Eclipse). If you are nevertheless compelled to override the `outputDirectory`, you should also look at the following options:
1. [clearOutputDirectory](https://www.xolstice.org/protobuf-maven-plugin/compile-mojo.html#clearOutputDirectory) -- this is set to `true` by default (for legacy reasons), and you will need to override it as `false`. This is most likely the reason your generated message classes are cleared out by `compile-custom` goal.
2. [checkStaleness](https://www.xolstice.org/protobuf-maven-plugin/compile-mojo.html#checkStaleness) -- if it is set to `true` in one of the parent POMs, it may interfere here too. On running the second goal, the plugin will detect that the generated sources are more recent than the `proto` file(s) and skip the goal execution. You can run `mvn help:effective-pom` to check the effective configuration of `protobuf-maven-plugin`.

I hope that helps.
Feel free to join the [Gitter](https://github.com/xolstice/protobuf-maven-plugin) chat if you have other questions.

Kind regards,
Sergei

**Comment by ejona86** [comment]
> To start with, I do not think that option java_multiple_files = true; is being honoured by gRPC code generator. To the best of my knowledge and belief, it only applies to generating java code for the messages (--java_out).

It is honored in that gRPC will use the correct protobuf class name. But yes, gRPC will still only use a single class for generation.

I'd also expect `clearOutputDirectory = false` to solve the problem.

**Comment by sergei-ivanov** [comment]
> > To start with, I do not think that option java_multiple_files = true; is being honoured by gRPC code generator. To the best of my knowledge and belief, it only applies to generating java code for the messages (--java_out).
> 
> It is honored in that gRPC will use the correct protobuf class name. But yes, gRPC will still only use a single class for generation.

@ejona86 That is a very good point, thank you for correcting me!

**Comment by sergei-ivanov** [comment]
Closing, in assumption that the problem was resolved through plugin configuration.

**Comment by skyrocknroll** [comment]
setting clearOutputDirectory = false worked for me. 
Effective pom.xml snippet
``` <build>
        <extensions>
            <extension>
                <groupId>kr.motd.maven</groupId>
                <artifactId>os-maven-plugin</artifactId>
                <version>1.4.1.Final</version>
            </extension>
        </extensions>
        <plugins>
            <plugin>
                <groupId>org.xolstice.maven.plugins</groupId>
                <artifactId>protobuf-maven-plugin</artifactId>
                <version>0.5.0</version>
                <configuration>
                    <protocArtifact>com.google.protobuf:protoc:3.0.2:exe:${os.detected.classifier}</protocArtifact>
                    <pluginId>grpc-java</pluginId>
                    <pluginArtifact>io.grpc:protoc-gen-grpc-java:1.2.0:exe:${os.detected.classifier}</pluginArtifact>
                    <outputDirectory>${basedir}/src/main/java</outputDirectory>
                    <clearOutputDirectory>false</clearOutputDirectory>
                    <!--<outputDirectory>${project.build.directory}/generated-sources/protobuf/java</outputDirectory>-->
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                            <goal>compile-custom</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```

**Comment by sergei-ivanov** [comment]
I would not recommend setting `outputDirectory` to `src/main/java` (which is very un-Maven in nature) or even overriding it at all.
If `outputDirectory` is not explicitly overridden, the plugin will automatically create subdirectories for the generated classes inside the `target` directory, and those subdirectories will be added to the list of source directories for the Maven project. Any intelligent IDE will also recognise these subdirectories as "source directories".

**Comment by rutuja-payr** [comment]
how to change the input directory from src/main/protocol

**Comment by sergei-ivanov** [comment]
@rutuja-payr Please see the [documentation](https://www.xolstice.org/protobuf-maven-plugin/compile-mojo.html#protoSourceRoot) provided.
